


package moodle;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import moodle17206.User;

/**
 *
 * @author 17206 Nathalia Braga
 */
public class NewStudent extends javax.swing.JFrame {

    /**
     * Creates new form NewStudent
     */

    studentIDU std = new studentIDU();

    public NewStudent() {
        initComponents();
        ShowSTudentTable();
        FillCombo();
//selectStudentInformations();
    }
    
    //making connection with database
     public Connection getConnection(){
      
      Connection con;
      
      try{
          con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Moodle17206Nathalia","root","Veralice13$");
          //JOptionPane.showMessageDialog(null, "Connected with Database");
          return con;
          
      }catch (Exception e){
          e.printStackTrace();
          return null;
      }
     }

     //making a list to create a class to bring all the informations in the Student database table for Java
     public ArrayList<User> selectStudentInformations(){
      
      ArrayList<User> studentInformations = new ArrayList<User>();
      Connection connection = getConnection();
      
      String selection = "SELECT * FROM Student";
      Statement st;
      ResultSet rs;
      
      try{
          st = connection.createStatement();
          rs = st.executeQuery(selection);
          User user;
          
          while(rs.next()){
              user = new User(rs.getString("StudentID"), rs.getString("StudentFName"), rs.getString("StudentLName"), rs.getString("StudentPhone"), rs.getString("Branch"), rs.getString("CourseName"));
              studentInformations.add(user);
              
          }
          
      }catch (Exception e){
          e.printStackTrace();
      }
      
      
      return studentInformations;
  }
     private void FillCombo(){
           try{
               String sql = "SELECT * FROM Course";
               Connection connection = getConnection();
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Moodle17206Nathalia","root","Veralice13$");
          
               pst = (PreparedStatement) con.prepareStatement(sql);
               rs = pst.executeQuery();
               
               while(rs.next()){
                   String course = rs.getString("CourseName");
                   comboCourse.addItem(course);
               }
           }   catch(Exception e){
           JOptionPane.showMessageDialog(null, e);    
           
          }}
    
     
     
    public void ShowSTudentTable(){
      
      ArrayList<User> list = selectStudentInformations();
      DefaultTableModel model = (DefaultTableModel) studRegTable.getModel();
      Object[] row = new Object[6];
      for(int i = 0; i < list.size(); i++){
          row[0] = list.get(i).getStudentID();
          row[1] = list.get(i).getStudentFName();
          row[2] = list.get(i).getStudentLName();
          row[3] = list.get(i).getStudentPhone();
          row[4] = list.get(i).getBranch();
          row[5] = list.get(i).getCourseName();
        
                  
          model.addRow(row);
          studRegTable.setShowGrid(true);
          studRegTable.setSelectionBackground(Color.green);
        }
  }
 
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        srFName = new javax.swing.JLabel();
        srLName = new javax.swing.JLabel();
        srSPhone = new javax.swing.JLabel();
        srSCourse = new javax.swing.JLabel();
        srCBranch = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        studRegFieldFName = new javax.swing.JTextField();
        studRegFieldLName = new javax.swing.JTextField();
        studRegFieldPhone = new javax.swing.JTextField();
        comboBranch = new javax.swing.JComboBox<>();
        comboCourse = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        studID = new javax.swing.JLabel();
        studRegFieldID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studRegTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        studRegFieldSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        srFName.setText("Student First Name");

        srLName.setText("Student Surname");

        srSPhone.setText("Student Phone");

        srSCourse.setText("Student Course");

        srCBranch.setText("College Branch");

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        studRegFieldLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studRegFieldLNameActionPerformed(evt);
            }
        });

        studRegFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studRegFieldPhoneActionPerformed(evt);
            }
        });
        studRegFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studRegFieldPhoneKeyTyped(evt);
            }
        });

        comboBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VGC 1", "VGC 2", "VGC 3" }));
        comboBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBranchActionPerformed(evt);
            }
        });

        comboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Accountance", "IT", "Business" }));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moodle/Icons/school.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("STUDENT REGISTRATION");

        studID.setText("Student ID");

        jButton3.setBackground(new java.awt.Color(255, 204, 51));
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(studRegFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(srFName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studRegFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(srLName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(studRegFieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(srSPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(studRegFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(srCBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(comboBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(srSCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(studRegFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srFName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(studRegFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srLName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(studRegFieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srSPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(studRegFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srCBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(comboBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(srSCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        studRegTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentID", "StudentFName", "StudentLName", "StudentPhone", "Branch", "Course"
            }
        ));
        studRegTable.setColumnSelectionAllowed(true);
        studRegTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studRegTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studRegTable);
        studRegTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        studRegFieldSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        studRegFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studRegFieldSearchActionPerformed(evt);
            }
        });
        studRegFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studRegFieldSearchKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel1.setText("Search for");
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel1KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 3, 18)); // NOI18N
        jLabel8.setText("VIRTUAL GLOBAL COLLEGE");

        jButton5.setBackground(new java.awt.Color(0, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jButton5.setText("REFRESH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studRegFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jButton5)
                        .addGap(66, 66, 66)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1804, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studRegFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Exit the Program
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBranchActionPerformed

    private void studRegFieldLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studRegFieldLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studRegFieldLNameActionPerformed

    private void studRegFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studRegFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studRegFieldPhoneActionPerformed

    private void studRegFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studRegFieldPhoneKeyTyped
        
        //just numbers are allowed to be typed in the Student Phone Field
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
        
    }//GEN-LAST:event_studRegFieldPhoneKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
   
        //Code to insert New Student in the table
                 DefaultTableModel model = (DefaultTableModel) studRegTable.getModel(); 
            if (!studRegFieldID.getText().trim().equals("")){
                model.addRow(new Object[]{
                    studRegFieldID.getText(),
                    studRegFieldFName.getText(),
                    studRegFieldLName.getText(),
                    studRegFieldPhone.getText(),
                    comboBranch.getSelectedItem(),
                    comboCourse.getSelectedItem(),
                    
                    
           });
            } else {
                JOptionPane.showMessageDialog(null, "It is missing Information");
                
            }
            
            
            String statement = "INSERT INTO Student VALUES(?,?,?,?,?,?)";    
        
       try{
            
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Moodle17206Nathalia","root","Veralice13$");
            pst = (PreparedStatement) con.prepareStatement(statement);
            
            //take the informations typed in the fields in the Student Registration
            pst.setString(1, studRegFieldID.getText());
            pst.setString(2, studRegFieldFName.getText());
            pst.setString(3, studRegFieldLName.getText());
            pst.setString(4, studRegFieldPhone.getText());
            pst.setString(5, (String) comboBranch.getSelectedItem());
            pst.setString(6, (String) comboCourse.getSelectedItem());
            
            
            //execute the new student in the table           
            if(pst.executeUpdate() > 0){
            
                JOptionPane.showMessageDialog(null, "New Student Inserted!");
            }
           
                        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void studRegTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studRegTableMouseClicked

        //When click in the information on one student, the student's information will be brought to the Fields to Add, Update or Delete
        int i = studRegTable.getSelectedRow();
        TableModel model = studRegTable.getModel();
        
        
        studRegFieldID.setText(model.getValueAt(i,0).toString());
        studRegFieldFName.setText(model.getValueAt(i,1).toString());
        studRegFieldLName.setText(model.getValueAt(i,2).toString());
        studRegFieldPhone.setText(model.getValueAt(i,3).toString());
        
        //There is a function not working as I can't bring the course and branch because they are combo
        //comboBranch.getSelectedItem(model.getValueAt(i,4).toString());
        //comboCourse.setText(model.getValueAt(i,5).toString());

    }//GEN-LAST:event_studRegTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //Update Code
        String sql = "UPDATE Student SET StudentFName=?, StudentLName=?, StudentPhone=?, Branch=?, CourseName=? WHERE (StudentID=?)";
       //UPDATE Student SET StudentFName='Na' WHERE StudentID='st1';
       
       //This code will print a new row with the alterations/ updated and it is going to delete the old information just when open it again
            DefaultTableModel model = (DefaultTableModel) studRegTable.getModel(); 
            if (!studRegFieldID.getText().trim().equals("")){
                model.addRow(new Object[]{
                    studRegFieldID.getText(),
                    studRegFieldFName.getText(),
                    studRegFieldLName.getText(),
                    studRegFieldPhone.getText(),
                    comboBranch.getSelectedItem(),
                    comboCourse.getSelectedItem(),
                    
           });
            } else {
                JOptionPane.showMessageDialog(null, "It is missing Information");
                
            }
            
      //Code updating the informations
        try{
                
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Moodle17206Nathalia","root","Veralice13$");
            pst = (PreparedStatement) con.prepareStatement(sql);
         
            pst.setString(6, studRegFieldID.getText());
            
            pst.setString(1, studRegFieldFName.getText());
            pst.setString(2, studRegFieldLName.getText());
            pst.setString(3, studRegFieldPhone.getText());
            pst.setString(4, (String) comboBranch.getSelectedItem());
            pst.setString(5, (String) comboCourse.getSelectedItem());
             
            //execute the new row with updated informations in the table           
            if(pst.executeUpdate() > 0){
              
                
                JOptionPane.showMessageDialog(null, "Check the old information and New Update!");          
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //Delete Code
            try{
            String sql = "DELETE FROM Moodle17206Nathalia.Student WHERE StudentID = ?";
            con = (Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/Moodle17206Nathalia","root","Veralice13$");
            pst = (PreparedStatement) con.prepareStatement(sql);
            pst.setString(1, studRegFieldID.getText());
                                                   
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Student Deleted!");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
            
        //I found my way to bring the table after Delete an information     
        this.dispose();
        //Refresh the Registration Form
        NewStudent ns = new NewStudent();
        ns.setVisible(true);
        ns.pack();
        ns.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void studRegFieldSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studRegFieldSearchKeyTyped
        
        
    }//GEN-LAST:event_studRegFieldSearchKeyTyped

    private void jLabel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyReleased
       studRegTable.setModel(new DefaultTableModel(null, new Object[]{"StudentID", "StudentFName","StudentLName","StudentPhone","Branch","CourseName"}));
       //studRegTable(showStudentTable, studRegFieldSearch.getText());
       //model(studRegTable, studRegFieldSearch.getText());
       //list(studRegTable, studRegFieldSearch.getText());
       //It does not work...
    }//GEN-LAST:event_jLabel1KeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

         this.dispose();
        //Refresh the Registration Form
        NewStudent ns = new NewStudent();
        ns.setVisible(true);
        ns.pack();
        ns.setLocationRelativeTo(null);

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void studRegFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studRegFieldSearchActionPerformed
      
        //Search the Student
        
    }//GEN-LAST:event_studRegFieldSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBranch;
    private javax.swing.JComboBox<String> comboCourse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel srCBranch;
    private javax.swing.JLabel srFName;
    private javax.swing.JLabel srLName;
    private javax.swing.JLabel srSCourse;
    private javax.swing.JLabel srSPhone;
    private javax.swing.JLabel studID;
    private javax.swing.JTextField studRegFieldFName;
    private javax.swing.JTextField studRegFieldID;
    private javax.swing.JTextField studRegFieldLName;
    private javax.swing.JTextField studRegFieldPhone;
    private javax.swing.JTextField studRegFieldSearch;
    private javax.swing.JTable studRegTable;
    // End of variables declaration//GEN-END:variables
}
